name: Feature request
description: Propose a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the user problem first, then the proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What problem are users facing today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: What should be built?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other approaches and why they were rejected.

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking change risk
      options:
        - No
        - Possibly
        - Yes
    validations:
      required: true
